(defparameter *SICK-SCHEMAS* '(

(EPI-SCHEMA ((?X_L (COMPOSITE-SCHEMA.PR ?X_M ?X_N ?X_O ?X_P ?X_Q ?X_R)) ** ?E)
	(:ROLES
		(!R1 (?X_Q MEDICINE.N))
		(!R2 (?X_P SICK.A))
		(!R3 (?X_O DIZZY.A))
		(!R4 (?X_N HEADACHE.N))
		(!R5 (?X_M HEAD.N))
		(!R6 (?X_M (PERTAIN-TO ?X_L)))
		(!R7 (?X_R WATER.N))
		(!R8 (?X_L AGENT.N))
		(!R9 (?X_R FOOD.N))
	)
	(:STEPS
		(?X_A (?X_L (SHAKE.V ?X_M)))
		(?X_I (?X_L (HAVE.V ?X_N)))
		(?X_G (?X_L (FEEL.V ?X_O)))
		(?X_E (?X_L (FEEL.V ?X_P)))
		(?X_C (?X_L (PUT_ON.V ?X_Q)))
		(?X_K (?X_L DRANK.3.V ?X_R))
	)
)
(EPI-SCHEMA ((?X_E (TAKE.V ?X_F)) ** ?E)
	(:ROLES
		(!R1 (?X_F TEST.N))
		(!R2 (?X_G SICK.A))
		(!R3 (?X_E MAN.N))
		(!R4 (?X_E SCARED.A))
		(!R5 (?X_E NERVOUS.A))
		(!R6 (?X_E (AFRAID.A (KA (FAIL.V ?X_F)))))
	)
	(:STEPS
		(?X_B (MUST.AUX-S (?X_E (TAKE.V ?X_F))))
		(?X_D (?X_E (FEEL.V ?X_G)))
		(E48.SK (NOT (?X_E (CAN.MD CONCENTRATE.V))))
	)
)
(EPI-SCHEMA ((?X_K (COMPOSITE-SCHEMA.PR ?X_L ?X_M ?X_N ?X_O)) ** ?E)
	(:ROLES
		(!R1 (?X_M SICK.A))
		(!R2 (?X_F PLATE.N))
		(!R3 (?X_O (PLUR SPAGHETTI.N)))
		(!R4 (?X_L ((PASV FORCE.V) (KA (EAT.V ?X_N)))))
		(!R5 (?X_N (PLUR SPAGHETTI.N)))
		(!R6 (?X AGENT.N))
		(!R7 (?X_K AGENT.N))
		(!R8 (?X_O OBJECT.N))
		(!R9 (NOT (?X_O ACTION.N)))
		(!R10 (NOT (?X_O AGENT.N)))
	)
	(:STEPS
		(?X_H (?X_A (KA SUE.V) (BE.V ?X_L)))
		(E266.SK (NOT (?X_K ((CAN.MD EAT.V) ?X_O))))
		(?E_1 (?X EAT.11.V ?X_N))
		(?X_J (?X_K HATE.6.V ?X_O))
		(?X_E (?X_K ((ADV-A (ON.P ?X_F)) THROW_UP.V)))
		(?X_C (?X_K (FEEL.V ?X_M)))
	)
)
(EPI-SCHEMA ((?X_G (EAT.V ?X_J)) ** ?E)
	(:ROLES
		(!R1 (?X_H SICK.A))
		(!R2 (?X_G BOY.N))
		(!R3 (?X_G HUNGRY.A))
		(!R4 (?X_J (TOO.ADV MUCH.A)))
		(!R5 (?X_I FOOD.N))
		(!R6 (?X_J FOOD.N))
	)
	(:STEPS
		(?X_D (?X_G EAT.4.V ?X_I))
		(?X_F (?X_G EAT.4.V ?X_J))
		(?X_B (?X_G (FEEL.V ?X_H)))
	)
)
(EPI-SCHEMA ((?X_G (COMPOSITE-SCHEMA.PR ?X_H ?X_I ?X_J)) ** ?E)
	(:ROLES
		(!R1 (?X_H SICK.A))
		(!R2 (?X_I DIZZY.A))
		(!R3 (?X_G BOY.N))
		(!R4 (?X_G NERVOUS.A))
		(!R5 (?X_G AFRAID.A))
		(!R6 (?X_G SCARED.A))
		(!R7 (?X_G WORRIED.A))
		(!R8 (?X_G ANXIOUS.A))
		(!R9 (?X_G SAD.A))
		(!R10 (?X_J SAD.A))
	)
	(:STEPS
		(?X_B (?X_G (FEEL.V ?X_H)))
		(?X_D (?X_G (FEEL.V ?X_I)))
		(?X_F (?X_G (FEEL.V ?X_J)))
	)
)
(EPI-SCHEMA ((?X_H (HELP.V ?X_H)) ** ?E)
	(:ROLES
		(!R1 (?X_H SICK.A))
		(!R2 (?X_H (PLUR PERSON.N)))
		(!R3 (?X_G MOM.N))
		(!R4 (?X_G NURSE.N))
		(!R5 (?X_D AGENT.N))
		(!R6 (?X_D PROUD.A))
		(!R7 (?X_G (PERTAIN-TO ?X_D)))
		(!R8 (?X_I MEDICINE.N))
	)
	(:STEPS
		(?X_A (?X_D (OF.P ?X_G)))
		(?X_C (?X_G (HELP.V ?X_H)))
		(?X_F (?X_G (GIVE.1.V ?X_H ?X_I)))
	)
)
(EPI-SCHEMA (((ADV-E ({DURING}.P (ALL.D DAY.N))) (?X_G SLEEP.V)) ** ?E)
	(:ROLES
		(!R1 (?X_H FEVER.N))
		(!R2 (?X_G BOY.N))
		(!R3 (?X_G SICK.A))
		(!R4 (?X_I BETTER.A))
	)
	(:STEPS
		(?X_B (?X_G (HAVE.V ?X_H)))
		(?X_D ((ADV-E ({DURING}.P (ALL.D DAY.N))) (?X_G SLEEP.V)))
		(?X_F (?X_G (FEEL.V ?X_I)))
	)
)
(EPI-SCHEMA (((ADV-E ({DURING}.P (ALL.D DAY.N))) (?X_F SLEEP.V)) ** ?E)
	(:ROLES
		(!R1 (?X_F FEVER.N))
		(!R2 (?X_E SICK.A))
		(!R3 (?X_E TIRED.A))
		(!R4 (?X_E AGENT.N))
	)
	(:STEPS
		(?X_B (?X_E (HAVE.V ?X_F)))
		(?X_D ((ADV-E ({DURING}.P (ALL.D DAY.N))) (?X_E SLEEP.V)))
	)
)
(EPI-SCHEMA ((?X_G THROW_UP.V) ** ?E)
	(:ROLES
		(!R1 (?X_H SICK.A))
		(!R2 (?X_I DIZZY.A))
		(!R3 (?X_G TIRED.A))
		(!R4 (?X_G THIRSTY.A))
		(!R5 (?X_G AGENT.N))
	)
	(:STEPS
		(?X_B (?X_G (FEEL.V ?X_H)))
		(?X_D (?X_G (FEEL.V ?X_I)))
		(E120.SK (NOT (?X_G (CAN.MD EAT.V))))
		(?X_F (?X_G THROW_UP.V))
	)
)
(EPI-SCHEMA ((?X_K (((ADV-A (IN.P ?X_C)) EAT.V) ?X_H)) ** ?E)
	(:ROLES
		(!R1 (?X_C BED.N))
		(!R2 (?X_P SICK.A))
		(!R3 (?X_P MOM.N))
		(!R4 (?X_D BREAKFAST.N))
		(!R5 (?X_Q SOUP.N))
		(!R6 (?X_Q (FOR.P ?X_D)))
		(!R7 (?X_G LUNCH.N))
		(!R8 (?X_H CHICKEN.N))
		(!R9 (?X_R (FOR.P ?X_G)))
		(!R10 (?X_R ?X_H SOUP.N))
		(!R11 (?X_K AGENT.N))
		(!R12 (?X_P (PERTAIN-TO ?X_K)))
		(!R13 (?X_L SUPPER.N))
		(!R14 (?X_M ORANGE.N))
		(!R15 (?X_S (FOR.P ?X_L)))
		(!R16 (?X_S ?X_M JUICE.N))
		(!R17 (?X_R FOOD.N))
		(!R18 (?X_S FOOD.N))
		(!R19 (?X_P AGENT.N))
	)
	(:STEPS
		(?X_B
   ((ADV-E ({DURING}.P (ALL.D DAY.N))) (?X_P ((ADV-A (IN.P ?X_C)) STAY.V))))
		(?X_F (?X_P EAT.1.V ?X_Q))
		(?X_J (?X_P EAT.1.V ?X_R))
		(?X_O (?X_P DRANK.2.V ?X_S))
	)
)
(EPI-SCHEMA ((?X_H (HAVE.V ?X_J)) ** ?E)
	(:ROLES
		(!R1 (?X_I BAD.A))
		(!R2 (?X_J FEVER.N))
		(!R3 (?X_H SICK.A))
		(!R4 (?X_H AGENT.N))
		(!R5 (?X_E BED.N))
	)
	(:STEPS
		(?X_B (?X_H (FEEL.V ?X_I)))
		(?X_D (?X_H (HAVE.V ?X_J)))
		(E228.SK (NOT (?X_H (CAN.MD EAT.V))))
		(E229.SK (NOT (?X_H (CAN.MD PLAY.V))))
		(?X_G
   ((ADV-E ({DURING}.P (ALL.D DAY.N))) (?X_H ((ADV-A (IN.P ?X_E)) STAY.V))))
	)
)
(EPI-SCHEMA ((?X_K (STAY.V ?X_K ?X_K)) ** ?E)
	(:ROLES
		(!R1 (?X_L AGENT.N))
		(!R2 (?X_G SCHOOL.N))
		(!R3 (?X_H HOME.N))
		(!R4 (?X_K SICK.A))
		(!R5 (?X_H (PERTAIN-TO ?X_K)))
		(!R6 (?X_M SOUP.N))
		(!R7 (?X_K AGENT.N))
	)
	(:STEPS
		(?X_F (?X_K ((ADV-A (TO.P ?X_H)) ((ADV-A (FROM.P ?X_G)) STAY.V))))
		(?X_J (?X_K EAT.1.V ?X_M))
		(?X_D (?X_K (WATCH.V ?X_L)))
		(?X_B ((ADV-E (DURING (ALL.D AFTERNOON.N))) (?X_K SLEEP.V)))
	)
)
(EPI-SCHEMA ((?X_E ((ADV-A (FOR.P (KA (HELP.V ?X_H)))) COME.V)) ** ?E)
	(:ROLES
		(!R1 (?X_E CONDITION.N))
		(!R2 (?X_H NURSE.N))
		(!R3 (?X_I CARE.N))
		(!R4 (?X_J SICK.A))
		(!R5 (?X_J WOMAN.N))
		(!R6 (?X_E (PERTAIN-TO ?X_J)))
		(!R7 (?L2 DESTINATION.N))
	)
	(:STEPS
		(E27.SK (NOT (?X_J ((CAN.MD ((ADV-A (OF.P ?X_J)) TAKE.V)) ?X_I))))
		(?X_G (?X_H ((ADV-A (FROM.P ?L1)) COME.1.V) ?L2))
		(?X_D (?X_H (HELP.V ?X_J)))
		(?X_B (?X_E IMPROVE.V))
	)
)
(EPI-SCHEMA ((?X_I (COMPOSITE-SCHEMA.PR ?X_H (THAT (?X_I (HAVE.V ?X_J))))) **
             ?E)
	(:ROLES
		(!R1 (?X_H PERSON.N))
		(!R2 (?X_I BOY.N))
		(!R3 (?X_E (PERTAIN-TO ?X_I)))
		(!R4 (?X_J STOMACH.N))
		(!R5 (?X_J UPSET.A))
	)
	(:STEPS
		(?X_B (?X_I (TRICK.V ?X_H)))
		(?X_D (?X_I ((ADV-A (FOR.P (KA SICK.A))) PRETEND.V)))
		(?X_G (?X_I (TELL.V ?X_H (THAT (?X_I (HAVE.V ?X_J))))))
	)
)
(EPI-SCHEMA ((?X_A (DOWN.ADV ((ADV-A (ON.P ?X_A)) LIE.V))) ** ?E)
	(:ROLES
		(!R1 (?X_A COUCH.N))
		(!R2 (?X_D SICK.A))
		(!R3 (?X_D AGENT.N))
	)
	(:STEPS
		(?X_C (?X_D (DOWN.ADV ((ADV-A (ON.P ?X_A)) LIE.V))))
		(E161.SK (NOT (?X_D (CAN.MD MOVE.V))))
	)
)
(EPI-SCHEMA ((?X_G (STAY.V ?X_G ?X_G)) ** ?E)
	(:ROLES
		(!R1 (?X_H WEAK.A))
		(!R2 (?X_I (PLUR SPORT.N)))
		(!R3 (?X_G BOY.N))
		(!R4 (?X_G SICK.A))
		(!R5 (?X_C HOME.N))
		(!R6 (?X_C (PERTAIN-TO ?X_G)))
		(!R7 (?X_D SCHOOL.N))
	)
	(:STEPS
		(?X_B (?X_G (FEEL.V ?X_H)))
		(E230.SK (NOT (?X_G ((CAN.MD PLAY.V) ?X_I))))
		(?X_F (?X_G ((ADV-A (TO.P ?X_C)) ((ADV-A (FROM.P ?X_D)) STAY.V))))
	)
)
(EPI-SCHEMA ((?X_K ((ADV-A (TO.P ?X_M)) COME.V)) ** ?E)
	(:ROLES
		(!R1 (?X_L TROUBLE.N))
		(!R2 (?X_K AGENT.N))
		(!R3 (?X_J MAN.N))
		(!R4 (?X_J SICK.A))
		(!R5 (?X_H POLICE.N))
		(!R6 (?X_M HOUSE.N))
		(!R7 (?X_M (PERTAIN-TO ?X_J)))
		(!R8 (?X_I AMBULANCE.N))
		(!R9 (?X_M DESTINATION.N))
		(!R10 (?X_H AGENT.N))
		(!R11 (?X_M SMALLER-THAN.N ?X))
		(!R12 (?X AGENT.N))
		(!R13 (?X_I AGENT.N))
		(!R14 (?L2 DESTINATION.N))
	)
	(:STEPS
		(?X_E (?X_J (CALL.V ?X_K)))
		(?X_C (?X_J (HAVE.V (KE (?X_L BREATHE.V)))))
		(?X_A (?X_H ((ADV-A (FROM.P ?L1)) COME.1.V) ?X_M))
		(?E_1 (?X TAKE.5.V ?X_M ?L2))
		(?X_G (?X_I ((ADV-A (FROM.P ?L1)) COME.4.V) ?L2))
	)
)
(EPI-SCHEMA ((?X_M (CALL.V ?X_N)) ** ?E)
	(:ROLES
		(!R1 (?X_L HOME.N))
		(!R2 (?X_P HEADACHE.N))
		(!R3 (?X_O BAD.A))
		(!R4 (?X_N SICK.A))
		(!R5 (?X_N IN.P))
		(!R6 (?X_L (PERTAIN-TO ?X_M)))
		(!R7 (?X_M AGENT.N))
		(!R8 (?L2 DESTINATION.N))
	)
	(:STEPS
		(?X_A (?X_M (CALL.V ?X_N)))
		(?X_K (?X_M (FEEL.V ?X_O)))
		(?X_I (NOT (?X_M ((ADV-A (FOR.P (KA (WELL.ADV FEEL.V)))) BE.V))))
		(?X_G (?X_M (HAVE.V ?X_P)))
		(?X_E (NOT (?X_M (WANT.V (KA ((ADV-A (TO.P (KA WORK.V))) GO.V))))))
		(?X_C (?X_M ((ADV-A (TO.P ?X_L)) ((ADV-A (FROM.P (KA WORK.V))) STAY.V))))
		(?E_1 (?X_M ((ADV-A (FROM.P ?L1)) GO.1.V) ?L2))
	)
)
(EPI-SCHEMA ((?X_J (CALL_IN.V ?X_K)) ** ?E)
	(:ROLES
		(!R1 (?X_K SICK.A))
		(!R2 (?X_K IN.P))
		(!R3 (?X_L HEADACHE.N))
		(!R4 (?X_G HOME.N))
		(!R5 (?X_J AGENT.N))
		(!R6 (?X_G (PERTAIN-TO ?X_J)))
		(!R7 (?X_M WORK.N))
	)
	(:STEPS
		(?X_B (?X_J (CALL.V ?X_K)))
		(?X_D (?X_J (HAVE.V ?X_L)))
		(?X_F (?X_J ((ADV-A (TO.P ?X_G)) ((ADV-A (FROM.P ?X_M)) STAY.V))))
		(?X_I (?X_J (MISS.V ?X_M)))
	)
)
(EPI-SCHEMA ((?X_F (CALL_IN.V ?X_G)) ** ?E)
	(:ROLES
		(!R1 (?X_G SICK.A))
		(!R2 (?X_G IN.P))
		(!R3 (?X_F AGENT.N))
		(!R4 (?X_C (PERTAIN-TO ?X_F)))
	)
	(:STEPS
		(?X_B (?X_F (CALL.V ?X_G)))
		(?X_E (?X_F (SAY.V ?X_H)))
	)
)
(EPI-SCHEMA ((?X_K (((ADV-A (FOR.P ?X_K)) CALL.V) ?X_J)) ** ?E)
	(:ROLES
		(!R1 (?X_L ((ADV-A (AFTER.P (KA ((ADV-A (FOR.P ?X_C)) SLEEP.V)))) BETTER.A)))
		(!R2 (?X_K FEVER.N))
		(!R3 (?X_J SICK.A))
		(!R4 (?X_J IN.P))
		(!R5 (?X_I ((TOO.ADV TIRED.A) (KA (PLAY.V ?X_H)))))
		(!R6 (?X_H BASEBALL.N))
		(!R7 (?X_I AGENT.N))
	)
	(:STEPS
		(?X_G (?X_I (CALL.V ?X_J)))
		(E111.SK (NOT (?X_I (CAN.MD ((ADV-A (TO.P (KA WORK.V))) COME.V)))))
		(?X_E (?X_I (HAVE.V ?X_K)))
		(?X_B (?X_I (FEEL.V ?X_L)))
		(?E_1 (?X_I PLAY.2.V))
	)
)
(EPI-SCHEMA ((?X_K (CALL_IN.V ?X_L)) ** ?E)
	(:ROLES
		(!R1 (?X_L SICK.A))
		(!R2 (?X_L IN.P))
		(!R3 (?X_M HEADACHE.N))
		(!R4 (?X_H HOME.N))
		(!R5 (?X_E WORK.N))
		(!R6 (?X_K AGENT.N))
		(!R7 (?X_H (PERTAIN-TO ?X_K)))
	)
	(:STEPS
		(?X_B (?X_K (CALL.V ?X_L)))
		(?X_D (?X_K (HAVE.V ?X_M)))
		(?X_G (?X_K ((ADV-A (TO.P ?X_H)) ((ADV-A (FROM.P ?X_E)) STAY.V))))
		(?X_J ((ADV-E (DURING (ALL.D AFTERNOON.N))) (?X_K SLEEP.V)))
	)
)
(EPI-SCHEMA ((?X_P (CALL_IN.V ?X_P)) ** ?E)
	(:ROLES
		(!R1 (?X_E WHILE.N))
		(!R2 (?X_H WORK.N))
		(!R3 (?X_M HOME.N))
		(!R4 (?X_R HEADACHE.N))
		(!R5 (?X_P SICK.A))
		(!R6 (?X_P IN.P))
		(!R7 (?X_M (PERTAIN-TO ?X_Q)))
		(!R8 (?X_Q AGENT.N))
		(!R9 (?L2 DESTINATION.N))
	)
	(:STEPS
		(?X_L (?X_Q (CALL.V ?X_P)))
		(?X_J (?X_Q (SAY.V (THT (?X_Q (HAVE.V ?X_R))))))
		(?X_G (?X_Q ((ADV-A (TO.P ?X_M)) ((ADV-A (FROM.P ?X_H)) STAY.V))))
		(?X_D (?X_Q ((ADV-A (FOR.P ?X_E)) SLEEP.V)))
		(?X_A (?X_Q WAKE_UP.V))
		(?X_B (?X_Q (BETTER.ADV FEEL.V)))
		(?X_O (?X_Q ((ADV-A (FROM.P ?L1)) GO.3.V) ?L2))
	)
)
(EPI-SCHEMA ((?X_K (CALL.V ?X_I)) ** ?E)
	(:ROLES
		(!R1 (?X_J BAD.A))
		(!R2 (?X_I SICK.A))
		(!R3 (?X_I IN.P))
		(!R4 (?X_K MAN.N))
		(!R5 (?X_H BOSS.N))
		(!R6 (?X_H (PERTAIN-TO ?X_K)))
		(!R7 ((KA (CALL.V (L X (AND (X IN.P) (X SICK.A))))) ACTION.N))
		(!R8 (?X_H AGENT.N))
		(!R9 (NOT (?X_H = ?X_K)))
	)
	(:STEPS
		(?X_G (?X_K (CALL.V ?X_I)))
		(?X_E (?X_K (FEEL.V ?X_J)))
		(?X_C (NOT (?X_K ((ADV-A (FOR.P (KA (WELL.ADV FEEL.V)))) BE.V))))
		(E223.SK (NOT (?X_K (CAN.MD WORK.V))))
		(?X_A (?X_H TELL.4.V ?X_K (KA (CALL.V (L X (AND (X IN.P) (X SICK.A)))))))
	)
)
(EPI-SCHEMA ((?X_K (CALL.V ?X_L)) ** ?E)
	(:ROLES
		(!R1 (?X_M ((ADV-A (AFTER.P (KA (EAT.V ?X_N)))) BETTER.A)))
		(!R2 (?X_E WORK.N))
		(!R3 (?X_J HOME.N))
		(!R4 (?X_L SICK.A))
		(!R5 (?X_L IN.P))
		(!R6 (?X_J (PERTAIN-TO ?X_K)))
		(!R7 (?X_N FOOD.N))
		(!R8 (?X_K AGENT.N))
	)
	(:STEPS
		(?X_I (?X_K (CALL.V ?X_L)))
		(?X_G (NOT (?X_K ((ADV-A (FOR.P (KA (WELL.ADV FEEL.V)))) BE.V))))
		(?X_D (?X_K ((ADV-A (TO.P ?X_J)) ((ADV-A (FROM.P ?X_E)) STAY.V))))
		(?X_B (?X_K (FEEL.V ?X_M)))
		(?E_1 (?X_K EAT.5.V ?X_N))
	)
)
(EPI-SCHEMA ((?X_G (TELL.V ?X_F (THT (?X_G SICK.A)))) ** ?E)
	(:ROLES
		(!R1 (?X_F BOSS.N))
		(!R2 (?X_G AGENT.N))
		(!R3 (?X_F (PERTAIN-TO ?X_G)))
		(!R4 (?X_B HOME.N))
		(!R5 (?X_B (PERTAIN-TO ?X_G)))
		(!R6 (?X_C WORK.N))
	)
	(:STEPS
		(?X_A (?X_G (TELL.V ?X_F (THAT (?X_G SICK.A)))))
		(?X_E (?X_G ((ADV-A (TO.P ?X_B)) ((ADV-A (FROM.P ?X_C)) STAY.V))))
	)
)
(EPI-SCHEMA ((?X_N (((ADV-A (FOR.P ?X_N)) CALL.V) ?X_O)) ** ?E)
	(:ROLES
		(!R1 (?X_M SICK.A))
		(!R2 (?X_M IN.P))
		(!R3 (?X_O HEADACHE.N))
		(!R4 (?X_P SORE.A))
		(!R5 (?X_P THROAT.N))
		(!R6 (?X_N AGENT.N))
		(!R7 (?X_I HOME.N))
		(!R8 (?X_I (PERTAIN-TO ?X_N)))
		(!R9 (?X_J WORK.N))
	)
	(:STEPS
		(?X_B (?X_N (CALL.V ?X_M)))
		(?X_D (?X_N (SAY.V (THT (?X_N (FEEL.V BAD.A))))))
		(?X_F (?X_N (HAVE.V ?X_O)))
		(?X_H (?X_N (HAVE.V ?X_P)))
		(E316.SK (NOT (?X_N ((CAN.MD EAT.V) (ANY.D THING.N)))))
		(?X_L (?X_N ((ADV-A (TO.P ?X_I)) ((ADV-A (FROM.P ?X_J)) STAY.V))))
	)
)
(EPI-SCHEMA ((?X_K (CALL.V ?X_I)) ** ?E)
	(:ROLES
		(!R1 (?X_I MOM.N))
		(!R2 (?X_J DAD.N))
		(!R3 (?X_H MOTHER.N))
		(!R4 (?X_H MOM.N))
		(!R5 (?X_I (PERTAIN-TO ?X_H)))
		(!R6 (?X_C (PERTAIN-TO ?X_H)))
		(!R7 (?X_L (IF.P (KE ((EVERY.D THING.N) OKAY.A)))))
		(!R8 (?X_K AGENT.N))
		(!R9 (?X_H (PERTAIN-TO ?X_K)))
		(!R10 (?X_J (PERTAIN-TO ?X_K)))
	)
	(:STEPS
		(?X_A (?X_K (CALL.V ?X_H)))
		(?X_B (?X_K (TELL.V ?X_I (THAT (?X_J SICK.A)))))
		(?X_E (?X_H (ASK.V ?X_K ?X_L)))
		(?X_G (?X_K (SAY.V ?X_M)))
	)
)
(EPI-SCHEMA ((?X_O (CATCH.V ?X_Q)) ** ?E)
	(:ROLES
		(!R1 (?X_R VET.N))
		(!R2 (?X_P BOX.N))
		(!R3 (?X_Q CAT.N))
		(!R4 (?X_Q (IN.P ?X_P)))
		(!R5 (?X_P LOCATION.N))
		(!R6 (?X_Q SMALLER-THAN.N ?X_O))
		(!R7 (?X_O AGENT.N))
		(!R8 (?X_R DESTINATION.N))
	)
	(:STEPS
		(?X_J (?X_O (CATCH.V ?X_Q)))
		(?X_L (?X_O PUT.1.V ?X_Q ?X_P))
		(?X_H (?X_O (CLOSE.V ?X_P)))
		(?X_F (?X_O (KEEP.V ?X_Q)))
		(?X_N (?X_O TAKE.5.V ?X_Q ?X_R))
		(?X_D (?X_R (EXAMINE.V ?X_Q)))
		(?X_B (?X_R (SAY.V (THT (?X_Q SICK.A)))))
	)
)
(EPI-SCHEMA ((?X_G (HAVE.V (KE (?X_H BREATHE.V)))) ** ?E)
	(:ROLES
		(!R1 (?X_H TROUBLE.N))
		(!R2 (?X_G SORE.A))
		(!R3 (?X_G THROAT.N))
		(!R4 (?X_F SICK.A))
		(!R5 (?X_F AGENT.N))
		(!R6 (?N NOISE.N))
	)
	(:STEPS
		(E15.SK (NOT (?X_F (CAN.MD TALK.V))))
		(?X_A (?X_F COUGH.1.V ?N))
		(?X_E (?X_F (HAVE.V ?X_G)))
		(?X_C (?X_F (HAVE.V (KE (?X_H BREATHE.V)))))
	)
)
(EPI-SCHEMA ((?X_F (AFTERWARDS.ADV (BETTER.ADV FEEL.V))) ** ?E)
	(:ROLES
		(!R1 (?X_F ((ADV-A (FOR.P ?X_E)) SICK.A)))
		(!R2 (?X_E WHILE.N))
		(!R3 (?N NOISE.N))
		(!R4 (?X_F AGENT.N))
		(!R5 ((K (AFTER.P (?X_F COUGH.V))) NOISE.N))
	)
	(:STEPS
		(?X_B (?X_F COUGH.1.V ?N))
		(?X_D (?X_F FEEL.4.V (K (AFTER.P (?X_F COUGH.V)))))
	)
)
(EPI-SCHEMA ((?X_F (((ADV-A (OF.P ?X_I)) TAKE.V) ?X_G)) ** ?E)
	(:ROLES
		(!R1 (?X_H FRIEND.N))
		(!R2 (?X_G CARE.N))
		(!R3 (?X_I SICK.A))
		(!R4 (?X_I DOG.N))
		(!R5 (?X_F AGENT.N))
		(!R6 (?X_I (PERTAIN-TO ?X_F)))
		(!R7 (?X_H (PERTAIN-TO ?X_F)))
		(!R8 (?L2 DESTINATION.N))
	)
	(:STEPS
		(E215.SK (NOT (?X_F ((CAN.MD ((ADV-A (OF.P ?X_I)) TAKE.V)) ?X_G))))
		(?X_A (?X_F (CALL.V ?X_H)))
		(?X_B (?X_H ((ADV-A (FROM.P ?L1)) COME_OVER.9.V) ?L2))
		(?X_C (?X_H ((ADV-A (AFTER.P ?X_I)) LOOK.V)))
		(?X_D (?X_H (FED.V ?X_I)))
		(?X_E (?X_H ((ADV-A (WITH.P ?X_I)) PLAY.V)))
	)
)
(EPI-SCHEMA ((?X_J
              (COMPOSITE-SCHEMA.PR ?X_K (KA (DRINK.V ?X_L)) ?X_L ?X_M ?X_N
               ?X_O))
             ** ?E)
	(:ROLES
		(!R1
   (?X_K ((ADV-A (AFTER.P (KA (((ADV-A (AT.P ?X_C)) DRINK.V) ?X_O)))) SICK.A)))
		(!R2 (?X_L BEER.N))
		(!R3 (?X_M BEER.N))
		(!R4 (?X_N BEER.N))
		(!R5 (?X_O BEER.N))
		(!R6 ((KA (DRINK.V ?X_L)) ACTION.N))
		(!R7 (?X_J AGENT.N))
	)
	(:STEPS
		(?X_E (?X_J LIKE.2.V (KA (DRINK.V ?X_L))))
		(?E_1 (?X_J DRINK.4.V ?X_L))
		(?X_G (?X_J DRANK.1.V ?X_M))
		(?X_I (?X_J DRANK.1.V ?X_N))
		(?X_B (?X_J (FEEL.V ?X_K)))
		(?E_2 (?X_J DRINK.4.V ?X_O))
	)
)
(EPI-SCHEMA ((?X_E DIE.V) ** ?E)
	(:ROLES
		(!R1 (?X_E WOMAN.N))
		(!R2 (?X_E OLD.A))
		(!R3 (?X_E SICK.A))
		(!R4 (?X_F SAD.A))
		(!R5
   (?X_G (BECAUSE.P (KE (?X_E ((ADV-A (FOR.P (KA (SOON.ADV DIE.V)))) GO.V))))))
	)
	(:STEPS
		(?X_B (?X_E DIE.V))
		(?X_D (?X_E (BE.V ?X_F ?X_G)))
	)
)
(EPI-SCHEMA ((?X_C DIE.V) ** ?E)
	(:ROLES
		(!R1 (?X_C SICK.A))
		(!R2 (?X_C OLD.A))
		(!R3 (?X_C SAD.A))
		(!R4 (?X_C TIRED.A))
		(!R5 (?X_C AGENT.N))
	)
	(:STEPS
		(?X_B (?X_C DIE.V))
	)
)
(EPI-SCHEMA ((?X_C DIE.V) ** ?E)
	(:ROLES
		(!R1 (?X_C MAN.N))
		(!R2 (?X_C SICK.A))
	)
	(:STEPS
		(E154.SK (NOT (?X_C (CAN.MD BREATHE.V))))
		(?X_B (?X_C DIE.V))
	)
)
(EPI-SCHEMA ((?X_F DIE.V) ** ?E)
	(:ROLES
		(!R1 (?X_E MAN.N))
		(!R2 (?X_E OLD.A))
		(!R3 (?X_E SICK.A))
		(!R4 (?X_E SAD.A))
		(!R5 (?X_F SAD.A))
		(!R6 (?X_G (BECAUSE.P (KE (?X_E ((ADV-A (FOR.P (KA DIE.V))) GO.V))))))
	)
	(:STEPS
		(?X_B (?X_E DIE.V))
		(?X_D (?X_E (BE.V ?X_F ?X_G)))
	)
)
(EPI-SCHEMA ((?X_I (EAT.V ?X_I)) ** ?E)
	(:ROLES
		(!R1 (?X_J BUG.N))
		(!R2 (?X_I MAN.N))
		(!R3 (?X_K SICK.A))
		(!R4 (?X_J FOOD.N))
		(!R5 (?X_K FOOD.N))
	)
	(:STEPS
		(?X_F (?X_I EAT.4.V ?X_J))
		(?X_D (?X_I ((ADV-A (ON.P ?X_J)) CHEW.V)))
		(?X_B (?X_I (SWALLOW.V ?X_J)))
		(?X_H (?X_I FEEL.5.V ?X_K))
	)
)
(EPI-SCHEMA ((?X_N (EAT.V ?X_Q)) ** ?E)
	(:ROLES
		(!R1 (?X_O ((ADV-A (AFTER.P (KA (EAT.V ?X_Q)))) SICK.A)))
		(!R2 (?X_Q INSECT.N))
		(!R3 (?X_P (PLUR INSECT.N)))
		(!R4 (?X_M BOY.N))
		(!R5 (?X_M ((PASV NAME.V) ?X_N)))
		(!R6 (NOT (?X_P ACTION.N)))
		(!R7 (?X_Q FOOD.N))
		(!R8 (?X_N AGENT.N))
	)
	(:STEPS
		(?X_H (?X_M EAT.4.V ?X_Q))
		(?X_J (?X_N LIKE.7.V ?X_P))
		(?X_L (?X_N EAT.4.V ?X_Q))
		(?X_F (?X_N (CHEW.V ?X_Q)))
		(?X_D (?X_N (SWALLOW.V ?X_Q)))
		(?X_B (?X_N (FEEL.V ?X_O)))
		(?E_1 (?X_N EAT.2.V ?X_Q))
	)
)
(EPI-SCHEMA ((?X_J THROW_UP.V) ** ?E)
	(:ROLES
		(!R1 (?X_C PLACE.N))
		(!R2 (?X_K SICK.A))
		(!R3 (?X_J BOY.N))
		(!R4 (?X_L BUG.N))
		(!R5 (?X_L FOOD.N))
		(!R6 (NOT (?O ACTION.N)))
		(!R7 (NOT (?O AGENT.N)))
		(!R8 (?O OBJECT.N))
	)
	(:STEPS
		(?X_I (?X_J EAT.4.V ?X_L))
		(?X_G (?X_J (FEEL.V ?X_K)))
		(?X_E (?X_J THROW_UP.V))
		(?X_B (?X_J ((ADV-A (FROM.P ?X_C)) (AWAY.ADV RUN.V))))
		(?E_1 (?X_J SCARE.8.V ?O))
	)
)
(EPI-SCHEMA ((?X_O (EAT.V ?X_R)) ** ?E)
	(:ROLES
		(!R1 (?X_P SICK.A))
		(!R2 (?X_E MALE.A))
		(!R3 (?X_E AGENT.N))
		(!R4 (?X_Q GRASS.N))
		(!R5 (?X_J GRASS.N))
		(!R6 (?X_R TASTE.N))
		(!R7 (?X_R (OF.P ?X_J)))
		(!R8 (?X_S MORE.A))
		(!R9 (?X_S GRASS.N))
		(!R10 (?X_O BOY.N))
		(!R11 (?X_Q FOOD.N))
		(!R12 (?X_R OBJECT.N))
		(!R13 (NOT (?X_R ACTION.N)))
		(!R14 (NOT (?X_R AGENT.N)))
		(!R15 (?X_S FOOD.N))
		(!R16
   ((ALL.D (L X (AND (X (PLUR {REF}.N)) (X (OF.P (THE.D GRASS.N)))))) FOOD.N))
	)
	(:STEPS
		(?X_G (?X_O EAT.1.V ?X_Q))
		(?X_I (?X_O LIKE.4.V ?X_R))
		(?X_L (?X_O EAT.1.V ?X_S))
		(?X_N
   (?X_O EAT.6.V
    (ALL.D (L X (AND (X (PLUR {REF}.N)) (X (OF.P (THE.D GRASS.N))))))))
		(?X_D (?X_E (FEEL.V ?X_P)))
		(?X_B (?X_E THROW_UP.V))
	)
)
(EPI-SCHEMA ((?X_M ((ADV-A (AFTER.P ?X_O)) THROW_UP.V)) ** ?E)
	(:ROLES
		(!R1 (?X_M BETTER.A))
		(!R2 (?X_L SICK.A))
		(!R3 (?X_K BOY.N))
		(!R4 (?X_K THIRSTY.A))
		(!R5 (?X_N GRASS.N))
		(!R6 (?X_O WATER.N))
		(!R7 (?X_N FOOD.N))
		(!R8 (?X_O FOOD.N))
	)
	(:STEPS
		(?X_H (?X_K EAT.1.V ?X_N))
		(?X_F (?X_K (FEEL.V ?X_L)))
		(?X_D (?X_K THROW_UP.V))
		(?X_J (?X_K DRANK.7.V ?X_O))
		(?X_B (?X_K (FEEL.V ?X_M)))
	)
)
(EPI-SCHEMA ((?X_L (EAT.V ?F ?X_K)) ** ?E)
	(:ROLES
		(!R1 (?X_L PIZZA.N))
		(!R2 (?X_C (TOO.ADV MANY.A)))
		(!R3 (?X_D PIZZA.N))
		(!R4 (?X_M ?X_C (PLUR SLICE.N)))
		(!R5 (?X_M (OF.P ?X_D)))
		(!R6 (?X_N (UNTIL.P (KE (?X_K (FEEL.V SICK.A))))))
		(!R7 ((KA (EAT.V ?X_L)) ACTION.N))
		(!R8 (?X_M FOOD.N))
		(!R9 ((K (UNTIL.P (?X_K (FEEL.V SICK.A)))) AGENT.N))
		(!R10 (?F FOOD.N))
		(!R11 (?X_K AGENT.N))
		(!R12 (?X_N FOOD.N))
	)
	(:STEPS
		(E77.SK (NOT (?X_K (CAN.MD ((ADV-A (FOR.P (KA EAT.V))) STOP.V)))))
		(?X_B (?X_K LIKE.2.V (KA (EAT.V ?X_L))))
		(?E_1 ((K (UNTIL.P (?X_K (FEEL.V SICK.A)))) EAT.3.V ?X_L))
		(?X_F (?X_K EAT.1.V ?X_M))
		(?X_H (?X_K EAT.4.V ?F))
		(?E_2 ((K (UNTIL.P (?X_K (FEEL.V SICK.A)))) EAT.5.V ?F))
		(?X_J (?X_K EAT.1.V ?X_N))
	)
)
(EPI-SCHEMA ((?X_F
              (COMPOSITE-SCHEMA.PR
               (ALL.D
                (L X (AND (X (PLUR {REF}.N)) (X (OVER.P (THE.D HOUSE.N))))))
               ?X_H))
             ** ?E)
	(:ROLES
		(!R1 (?X_F BOY.N))
		(!R2 (?X_F ((ADV-A (FOR.P ?X_C)) SICK.A)))
		(!R3 (?X_C WEEK.N))
		(!R4 (?X_H (TOO.ADV MUCH.A)))
		(!R5 (?X_H PIZZA.N))
	)
	(:STEPS
		(?X_E (?X_F EAT.1.V ?X_H))
		(?X_B
   (?X_F
    (THROW_UP.V
     (ALL.D (L X (AND (X (PLUR {REF}.N)) (X (OVER.P (THE.D HOUSE.N)))))))))
	)
)

))
