FROM hltcoe/lome

RUN /opt/anaconda3/envs/spanfinder/bin/pip3 install torch==1.9.1+cu111 torchvision==0.10.1+cu111 torchaudio==0.9.1 -f https://download.pytorch.org/whl/torch_stable.html
RUN /opt/anaconda3/envs/hiertype/bin/pip3 install torch==1.9.1+cu111 torchvision==0.10.1+cu111 torchaudio==0.9.1 -f https://download.pytorch.org/whl/torch_stable.html
RUN /opt/anaconda3/envs/concrete-coref/bin/pip3 install torch==1.9.1+cu111 torchvision==0.10.1+cu111 torchaudio==0.9.1 -f https://download.pytorch.org/whl/torch_stable.html

RUN /opt/anaconda3/envs/time_ta2/bin/pip3 install torch==1.9.1+cu111 torchvision==0.10.1+cu111 torchaudio==0.9.1 -f https://download.pytorch.org/whl/torch_stable.html
RUN /opt/anaconda3/envs/time_ta2/bin/pip3 install transformers==4.4.2
